version: '3.8'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY = ${SECRET_KEY}
      - ALGORITHM = ${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES =${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DB_USERNAME = ${DB_USERNAME}
      - DB_PASSWORD = ${DB_PASSWORD}
      - DB_HOST = ${DB_HOST}
      - DB_PORT = ${DB_PORT}
      - DB_NAME = ${DB_NAME}
      - DB_DRIVER = ${DB_DRIVER}
    volumes:
      - ./:./usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
   
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: 4042
      - POSTGRES_DB: finance
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432